name: Build and Publish

on:
  push:
    tags:
      - '*'  # trigger on any tag push

jobs:
  build:
    name: Build and Publish Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        shell: bash
        run: |
          STATIC_PATH="static"
          TEMPLATES_PATH="templates"
      
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pyinstaller --onefile --name "PS4 Remote Installer" --windowed \
              --add-data "${STATIC_PATH};static" \
              --add-data "${TEMPLATES_PATH};templates" \
              src/main.py
          else
            pyinstaller --onefile --name "PS4 Remote Installer" --windowed \
              --add-data "${STATIC_PATH}:static" \
              --add-data "${TEMPLATES_PATH}:templates" \
              src/main.py
          fi


      - name: Upload Executable to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: ${{ matrix.os == 'windows-latest' && 'dist/PS4 Remote Installer.exe' || 'dist/PS4 Remote Installer' }}
          asset_name: ${{ matrix.os == 'windows-latest' && 'PS4 Remote Installer.exe' || 'PS4 Remote Installer' }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "PS4 Remote Installer for ${{ matrix.os }}"
